package com.scm.model;

/** Recommendation - suggested alternative vendor generated by RecommendationService. */
public class Recommendation {
    private int recId;
    private int alertId;
    private int suggestedVendorId;
    private String reason;

    public Recommendation() {}
    public Recommendation(int recId, int alertId, int suggestedVendorId, String reason) {
        this.recId = recId; this.alertId = alertId;
        this.suggestedVendorId = suggestedVendorId; this.reason = reason;
    }

    public int getRecId()                       { return recId; }
    public void setRecId(int id)                { this.recId = id; }
    public int getAlertId()                     { return alertId; }
    public void setAlertId(int id)              { this.alertId = id; }
    public int getSuggestedVendorId()           { return suggestedVendorId; }
    public void setSuggestedVendorId(int id)    { this.suggestedVendorId = id; }
    public String getReason()                   { return reason; }
    public void setReason(String r)             { this.reason = r; }
}
